# Generated by Django 4.0.4 on 2022-05-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdStatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=200, unique=True)),
                ('sBD', models.DateField()),
                ('gpa', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=500)),
                ('level', models.CharField(max_length=10)),
                ('Dpt', models.CharField(max_length=200)),
                ('sgpa', models.CharField(max_length=200)),
            ],
        ),
    ]
