# Generated by Django 4.0.4 on 2022-05-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Dpt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
