# Generated by Django 4.0.4 on 2022-05-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_sid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='student',
            name='Status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.IntegerField(),
        ),
    ]
