# Generated by Django 4.0.4 on 2022-05-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_delete_status_student_status_student_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Status',
            new_name='stat',
        ),
    ]
